config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # routes for ui kit
  get '/ui_kit', to: 'pages#ui_kit'
  get 'onboarding', to: 'pages#onboarding'
  get '/dashboard', to: 'pages#dashboard'
  post '/connections', to: 'connections#create', as: 'connections'
  get '/certificate', to: 'pages#certificate'



  resources :mentees, only: [:new, :create, :show, :update]
  resources :mentors, only: [:new, :create, :show, :index]

  resources :mentees, only: [:new, :create, :show]
  resources :mentors, only: [:new, :create, :show, :index] do
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews, only: [:show]

  resources :connections, only: [:show] do
    resources :tasks, only: [:index, :new, :create,:show, :destroy,:update]
  end

  resources :tasks, only: [:edit ]
  put 'mark_as_done/:id', to: 'tasks#mark_as_done', as: :mark_as_done_task

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  # resources :tasks do
  #   member do
  #     put 'mark_as_done', to: 'tasks#mark_as_done'
  #   end
  # end
  #   resources :mentors, only: []
  #   resources :rejected, only: []
  # end
  # resources :connections, only: [] do
  #   resources :tasks, only: []
  # end
  # resources :chatrooms, only: [] do
  #   resources :messages, only: []
  # end
  # Defines the root path route ("/")
  # root "posts#index"

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :connection

  validates :end_date, presence: true
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @connection = Connection.find(params[:connection_id])
    @tasks = @connection.tasks.order(:end_date)
    @mentee = @connection.mentee
  end

  def new
    @task = Task.new
    @connection = Connection.find(params[:connection_id])
  end

  def create
    @task = Task.new(task_params)
    @task.completed = false
    @connection = Connection.find(params[:connection_id])
    @task.connection = @connection
    @task.save

    redirect_to connection_tasks_path(@connection)
  end

  def show
    @connection = Connection.find(params[:connection_id])
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
    @connection = @task.connection
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    @connection = @task.connection

    redirect_to connection_tasks_path(@connection)
  end

  def mark_as_done
    @task = Task.find(params[:id])
    @connection = @task.connection
    @task.completed = true
    @task.save

    redirect_to connection_tasks_path(@connection), notice: 'Task done.'
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    @connection = Connection.find(params[:connection_id])

    redirect_to connection_tasks_path(@connection), status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :end_date)
  end
end

app/views/tasks/edit.html.erb
<div class="container px-4 mt-4">

  <%= simple_form_for([@connection, @task], html: { method: :put, multipart: true }) do |f| %>
    <div class="form-inputs text-center">
      <%= f.input :title,
                  required: false,
                  placeholder: "Title of task",
                  input_html: { autocomplete: "title", class: "input_html" } %>
      <%= f.input :description,
                  required: false,
                  placeholder: "Description of task",
                  input_html: { autocomplete: "description", class: "input_html" } %>
      <%= f.input :end_date,
                  required: false,
                  placeholder: "End date",
                  input_html: { autocomplete: "end_date", class: "input_html" } %>
    </div>

    <div class="form-actions d-flex justify-content-center">
      <%= f.button :submit, "Save", name: 'commit_save', class: "btn btn-ghost btn-submit", id:"btn-prim" %>
    </div>
  <% end %>

  <div class="text-center mt-3">
    <%= link_to "Delete", connection_task_path(@connection, @task), data: { "turbo-method": :delete }, class: " btn btn-ghost btn-submit btn-secun" %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container px-4 mt-2">
  <div class="container px-4 mb-2">
    <br>
    <div class="card-goal">
      <div class="card-small-infos">
        <h5>I am going to: </h5>
        <h1 class="task-goal"><strong><%= @mentee.goal %></strong></h1>
      </div>
      <div class="row">
        <div class="col-12 d-flex justify-content-center ">
          <strong><%= link_to "Add a task", new_connection_task_path, class: "btn btn-ghost btn-submit align-items-center btn-tasks" %></strong>
        </div>
      </div>
    </div>
    <br>

    <% @tasks.each do |task| %>
      <% if task.completed %>
        <div class="card-small-gray-task-done">
        <% else %>
          <div class="card-small-gray-task-todo">
          <% end %>
          <div class="d-flex flex-column" style="width: 180px;">
            <strong><%= link_to task.title.capitalize, connection_task_path(@connection, task), class: "task" %></strong>
            <i style="font-size: 0.9em;"><%= task.end_date.strftime("%d-%m-%Y") %></i>
          </div>
          <%= link_to edit_task_path(task), class: 'edit-task-button' do %>
            <svg class="task-icons" width="34" height="34" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"/></svg>
          <% end %>
          <%= link_to mark_as_done_task_path(task), data: { turbo_method: :put }, class: 'mark-as-done-button' do %>
                <% if task.completed %>
            <svg xmlns="http://www.w3.org/2000/svg" class="task-icons" width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>
                    <% else %>
          <svg xmlns="http://www.w3.org/2000/svg" class="task-icons" width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg>
            <%# <--- make button disappear/ disabled when task is done----> %>
          <% end %>
          <% end %>
        </div>
      <% end %>


      <%# I DID IT BUTTON %>
      <% if @tasks.any? { |task| !task.completed } %>
        <div class="card-small card-small-green-ultimate-goal" style="display: none;">
          <div class="card-small-infos text-center align-items-center">
          </div>
        </div>
      <% else %>
        <%= link_to certificate_path, class: "text-decoration-none" do %>
          <div class="card-small-green-ultimate-goal">
            <div class="card-small-infos" class="col-12 d-flex justify-content-center ">
              <h5 class="m-0 pb-0">Reached ultimate goal! </h5>
              <svg xmlns="http://www.w3.org/2000/svg" class="reached-icons" width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>
            </div>
          </div>
        <% end %>
      <% end %>
      <br>
    </div>
    <br>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container px-4 mt-4">

  <%= simple_form_for([@connection, @task], html: { multipart: true }) do |f| %>
  <div class="form-inputs text-center">
    <%= f.input :title,
                required: false,
                placeholder: "title of task",
                input_html: { autocomplete: "title", class:"input_html text-center" } %>
    <%= f.input :description,
                required: false,
                placeholder: "description of task",
                input_html: { autocomplete: "description", class:"input_html text-center" } %>
    <%= f.input :end_date,
                required: false,
                placeholder: "end date",
                input_html: { autocomplete: "end_date", class:"input_html text-center" } %>
      <div class="form-actions">
      <strong><%= f.button :submit, "Create task", class: "btn btn-ghost btn-submit row justify-content-center", id:"createtask" %></strong>
      </div>
  <% end %>
</div>
</div>
</div>

app/views/tasks/show.html.erb
<div class="tasks-container px-4 mt-4">

  <h2><%= @task.title.capitalize %></h2>
  <br>
  <p><strong>Description of task: </strong></p>
  <p><%= @task.description.capitalize %></p>
  <p><strong>Deadline of task:</strong></p>
    <p><i style="font-size: 0.9em;"><%= @task.end_date.strftime("%d-%m-%Y") %></i></p>




    <%= link_to "Edit", edit_task_path, class: "btn btn-submit btn-ghost d-flex align-items-center justify-content-center"%>
    <br>
    <%= link_to "Delete",connection_task_path(@connection, @task),
                  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-ghost btn-task-delete d-flex align-items-center justify-content-center"%>
    <br>
    <%= link_to "Back to tasks",connection_tasks_path(@connection), class: "btn btn-submit btn-ghost d-flex align-items-center justify-content-center" %>

</div>