config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # routes for ui kit
  get '/ui_kit', to: 'pages#ui_kit'
  get 'onboarding', to: 'pages#onboarding'
  get '/dashboard', to: 'pages#dashboard'
  post '/connections', to: 'connections#create', as: 'connections'
  get '/certificate', to: 'pages#certificate'



  resources :mentees, only: [:new, :create, :show, :update]
  resources :mentors, only: [:new, :create, :show, :index]

  resources :mentees, only: [:new, :create, :show]
  resources :mentors, only: [:new, :create, :show, :index] do
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews, only: [:show]

  resources :connections, only: [:show] do
    resources :tasks, only: [:index, :new, :create,:show, :destroy,:update]
  end

  resources :tasks, only: [:edit ]
  put 'mark_as_done/:id', to: 'tasks#mark_as_done', as: :mark_as_done_task

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  # resources :tasks do
  #   member do
  #     put 'mark_as_done', to: 'tasks#mark_as_done'
  #   end
  # end
  #   resources :mentors, only: []
  #   resources :rejected, only: []
  # end
  # resources :connections, only: [] do
  #   resources :tasks, only: []
  # end
  # resources :chatrooms, only: [] do
  #   resources :messages, only: []
  # end
  # Defines the root path route ("/")
  # root "posts#index"

end

app/models/mentee.rb
class Mentee < ApplicationRecord
  belongs_to :user

  has_one :connection, dependent: :destroy
  validates :goal, presence: true

  def index
    @mentors = Mentor.all
  end
end

app/controllers/mentees_controller.rb
class MenteesController < ApplicationController
  def new
    @mentee = Mentee.new
  end

  def create
    @mentee = Mentee.new(mentee_params)
    @mentee.user = current_user
    @mentee.save

    redirect_to root_path
  end

  def show
    @mentee = Mentee.find(params[:id])
    @connection
  end


  def update
    @mentee = Mentee.find(params[:id])
    @mentee.update(mentee_params)
      # No need for app/views/restaurants/update.html.erb
    redirect_to dashboard_path
  end


  private

  def mentee_params
    params.require(:mentee).permit(:goal)
  end
end

app/views/mentees/_my_mentors.html.erb
<div class="container px-4">
<br>
  <h4 class="mt-0 mb-4">My Mentor</h4>

  <div class="card-small card-small-green">
    <% if @connection %>
      <%= link_to connection_path(@connection) do %>
        <%= image_tag @connection.mentor.user.avatar_url, class: "avatar-home" %>
      <% end %>
    <% end %>
    <div class="card-small-infos">
      <% if @connection %>
      <%= link_to connection_path(@connection)do %>
        <h4 class="user-home"><%= @connection.mentor.user.first_name %></h4>
        <%end%>
      <% else %>
        <h4><%= link_to 'choose your mentor', mentors_path %></h4>
      <% end %>
    </div>
    <% if @connection %>
      <%= link_to chatroom_path(Chatroom.last) do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="message-icon-mentor" width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"/></svg>
      <% end %>
      <%= link_to connection_tasks_path(@connection) do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="timeline-icon-mentor" width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>
      <% end %>
    <% end %>
  </div>

  <hr class="mt-5 mb-4">

  <div class="mt-5">
    <h4 class="mt-0 mb-4"> Previous Mentors</h4>

    <% @random_mentors.each do |mentor| %>
      <div class="card-home">
        <%= link_to mentor_path(mentor) do %>
          <%= image_tag mentor.user.avatar_url, class: "avatar-home" %>
        <% end %>
        <div class="card-small-infos">
          <h4 class="gray-username"><%= mentor.user.first_name %></h4>
        </div>
          <svg xmlns="http://www.w3.org/2000/svg" class="message-icon-gray" width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"/></svg>
                  <svg xmlns="http://www.w3.org/2000/svg" class="timeline-icon" width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>
      </div>
    <% end %>
  </div>

</div>

app/views/mentees/_show.html.erb
<div class="container px-4 mt-4">
<h3 class="mt-0 mb-4">My Mentor</h3>

<div class="card-small card-small-green">
  <%= link_to "picture of user", "#" %>
  <div class="card-small-infos">
    <h2>user name</h2>
    <%= link_to chatroom_path(Chatroom.last) do %>
      <i class="fa-regular fa-message fa-3x"></i>
    <% end %>
    <p> 🏆</p>
  </div>
</div>

<br>

<h3 class="mt-0 mb-4"> Previous Mentors</h3>

    <div class="card-small-gray">
      <%= link_to "picture of user", "#"%>
        <div class="card-small-infos">
          <h2>user name</h2>
          <p>💬   🏆</p>
        </div>
    </div>

    <div class="card-small-gray">
      <%= link_to "picture of user", "#"%>
        <div class="card-small-infos">
          <h2>user name</h2>
          <p>💬   🏆</p>
        </div>
    </div>
      <div class="card-small-gray">
      <%= link_to "picture of user", "#"%>
        <div class="card-small-infos">
          <h2>user name</h2>
          <p>💬   🏆</p>
        </div>
    </div>

  </div>

app/views/mentees/_show_mentor.html.erb
<% if current_user === @mentee.user %>
    <% photo = @mentor.user.avatar_url %>
<% else %>
    <% photo = @mentee.user.avatar_url %>
<% end %>



 <div class="col-xl-8 mt-2 text-center">

     <div class="card-header"></div>
      <div class="card-body text-center">
                    <!-- Profile picture image-->
        <img class="avatar rounded-circle mb-2" src="<%= photo %>" alt="">

      </div>

<br>
            <!-- Account details card-->
                    <form>
                        <!-- Form first name (username)-->
                        <div class="mb-3">
                          <p>First name</p>
                          <input class="form-control input_html text-center" id="inputFirstName" type="text" placeholder="<%= @mentor.user.first_name %>" disabled>
                        </div>
                        <!-- Form last-name-->
                        <div class="mb-3">
                          <p>Last name</p>
                          <input class="form-control input_html text-center" id="inputLastName" type="text" placeholder="<%= @mentor.user.last_name %>" disabled>
                        </div>
                        <!-- Form email-->
                        <div class="mb-3">
                          <p>Email</p>
                          <input class="form-control input_html text-center" id="inputEmail" type="text" placeholder="<%= @mentor.user.email %>" disabled>
                        </div>
                        <!-- Form company-->
                        <div class="mb-3">
                          <p>Company</p>
                          <input class="form-control input_html text-center" id="inputCompany" type="text" placeholder="<%= value=@mentor.company %>" disabled>
                        </div>
                        <!-- Form job-title-->
                        <div class="mb-3">
                          <p>Job title</p>
                          <input class="form-control input_html text-center" id="inputJobTitle" type="text" placeholder="<%= value=@mentor.job_title %>" disabled>
                        </div>
                        <!-- Form location-->
                        <div class="mb-3">
                          <p>Location</p>
                          <input class="form-control input_html text-center" id="inputLocation" type="text" placeholder="Enter your location" value="Amsterdam" disabled>
                        </div>
                        <!-- Form bio-->
                        <div class="mb-3">
                          <p>Bio</p>
                          <input class="form-control input_html text-center" id="inputBio" type="text" placeholder="write bio" value="11 years experience as wedeveloper" disabled>
                        </div>

                    </form>
  </div>

app/views/mentees/index.html.erb
 <% @mentors.each do |mentor| %>
  <% if mentor.accepted?%>
          <%= cl_image_tag mentor.photo.key, class:"card-img", height: 300 %>
        <% end %>
<%end%>

app/views/mentees/new.html.erb
<div class="container px-4 mt-4">
  <h2>Mentee</h2>
    <hr class="mt-0 mb-4">

  <%= simple_form_for(@mentee, html: { multipart: true }) do |f| %>
  <div class="form-inputs text-center">
    <%= f.input :goal,
                required: false,
                placeholder: "(be explicit)",
                input_html: { autocomplete: "location", class:"input_html text-center" } %>
      <div class="form-actions">
      <%= f.button :submit, "Create account", class: "btn btn-ghost btn-submit row justify-content-center" %>
      </div>
  <% end %>
  </div>
</div>

app/views/mentees/show.html.erb
<div class="container px-4 mt-4">
<h3 class="mt-0 mb-4">My Mentor</h3>

<div class="card-small card-small-green">
  <%= link_to "picture of user", "#" %>
  <div class="card-small-infos">
    <h2>user name</h2>
    <p>💬 🏆</p>
  </div>
</div>

<br>

<h3 class="mt-0 mb-4"> Previous Mentors</h3>

    <div class="card-small-gray">
      <%= link_to "picture of user", "#"%>
        <div class="card-small-infos">
          <h2>user name</h2>
          <p>💬   🏆</p>
        </div>
    </div>

    <div class="card-small-gray">
      <%= link_to "picture of user", "#"%>
        <div class="card-small-infos">
          <h2>user name</h2>
          <p>💬   🏆</p>
        </div>
    </div>
      <div class="card-small-gray">
      <%= link_to "picture of user", "#"%>
        <div class="card-small-infos">
          <h2>user name</h2>
          <p>💬   🏆</p>
        </div>
    </div>
</div>