config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # routes for ui kit
  get '/ui_kit', to: 'pages#ui_kit'
  get 'onboarding', to: 'pages#onboarding'
  get '/dashboard', to: 'pages#dashboard'
  post '/connections', to: 'connections#create', as: 'connections'
  get '/certificate', to: 'pages#certificate'



  resources :mentees, only: [:new, :create, :show, :update]
  resources :mentors, only: [:new, :create, :show, :index]

  resources :mentees, only: [:new, :create, :show]
  resources :mentors, only: [:new, :create, :show, :index] do
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews, only: [:show]

  resources :connections, only: [:show] do
    resources :tasks, only: [:index, :new, :create,:show, :destroy,:update]
  end

  resources :tasks, only: [:edit ]
  put 'mark_as_done/:id', to: 'tasks#mark_as_done', as: :mark_as_done_task

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  # resources :tasks do
  #   member do
  #     put 'mark_as_done', to: 'tasks#mark_as_done'
  #   end
  # end
  #   resources :mentors, only: []
  #   resources :rejected, only: []
  # end
  # resources :connections, only: [] do
  #   resources :tasks, only: []
  # end
  # resources :chatrooms, only: [] do
  #   resources :messages, only: []
  # end
  # Defines the root path route ("/")
  # root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :connection
  has_many :messages, dependent: :destroy
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :mentee
  belongs_to :mentor
  has_many :tasks, dependent: :destroy
  has_one :chatroom, dependent: :destroy
end

app/models/mentee.rb
class Mentee < ApplicationRecord
  belongs_to :user

  has_one :connection, dependent: :destroy
  validates :goal, presence: true

  def index
    @mentors = Mentor.all
  end
end

app/models/mentor.rb
class Mentor < ApplicationRecord
  belongs_to :user
  has_one :connection, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :job_title, presence: true
  validates :company, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  def sender?(a_user)
    user.id == a_user.id
  end
end

app/models/rejected.rb
class Rejected < ApplicationRecord
  belongs_to :mentee
  belongs_to :mentor
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :mentor
  validates :rating, presence: true, inclusion: { in: 1..5 }

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :connection

  validates :end_date, presence: true
  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def role
    if Mentor.find_by(user_id: id)
      return "mentor"
    elsif Mentee.find_by(user_id: id)
      return "mentee"
    end
  end
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_one :mentor
  has_one :mentee

  def is_mentor?
    self.mentor != nil
  end

  def is_mentee?
    self.mentee != nil
  end

  def name
    return "#{first_name} #{last_name}"
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    # @chatroom = Chatroom.call(connection.chatroom)
    @message = Message.new
  end
end

app/controllers/mentees_controller.rb
class MenteesController < ApplicationController
  def new
    @mentee = Mentee.new
  end

  def create
    @mentee = Mentee.new(mentee_params)
    @mentee.user = current_user
    @mentee.save

    redirect_to root_path
  end

  def show
    @mentee = Mentee.find(params[:id])
    @connection
  end


  def update
    @mentee = Mentee.find(params[:id])
    @mentee.update(mentee_params)
      # No need for app/views/restaurants/update.html.erb
    redirect_to dashboard_path
  end


  private

  def mentee_params
    params.require(:mentee).permit(:goal)
  end
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController

  def index
    @mentors = Mentor.all
    @connection = Connection.new
    @reviews = Review.all
  end

  def new
    @mentor = Mentor.new
  end

  def create
    @mentor = Mentor.new(mentor_params)
    @mentor.user = current_user
    @mentor.save

    redirect_to root_path
  end

  def show
    @mentor = Mentor.find(params[:id])
  end

  private

  def mentor_params
    params.require(:mentor).permit(:job_title, :company)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        message: render_to_string(partial: "message", locals: { message: @message }),
        sender_id: @message.user.id
      )
      head :ok
    end
  end

  private

  def message_params
  params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @current_user_role = current_user.role
    if @current_user_role == "mentee"
     @connection = current_user.mentee.connection
     @random_mentors = Mentor.all.sample(3)
    else
      @connection = current_user.mentor.connection
    end

  end

  def ui_kit
  end

  def onboarding
  end

  def dashboard
   @user = current_user
   @mentee = current_user.mentee
   @token = form_authenticity_token
  end

  def certificate
    # @connection = current_user.mentor.connection
    @connection = current_user.mentee.connection
  end
end

app/controllers/rejects_controller.rb
class RejectsController < ApplicationController

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @mentor = Mentor.find_by(id: params[:mentor_id])
    @reviews = @mentor.reviews
  end

  def new
    # @mentor = Mentor.find_by(id: params[:mentor_id])
    @review = Review.new
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @connection = Connection.find(params[:connection_id])
    @tasks = @connection.tasks.order(:end_date)
    @mentee = @connection.mentee
  end

  def new
    @task = Task.new
    @connection = Connection.find(params[:connection_id])
  end

  def create
    @task = Task.new(task_params)
    @task.completed = false
    @connection = Connection.find(params[:connection_id])
    @task.connection = @connection
    @task.save

    redirect_to connection_tasks_path(@connection)
  end

  def show
    @connection = Connection.find(params[:connection_id])
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
    @connection = @task.connection
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    @connection = @task.connection

    redirect_to connection_tasks_path(@connection)
  end

  def mark_as_done
    @task = Task.find(params[:id])
    @connection = @task.connection
    @task.completed = true
    @task.save

    redirect_to connection_tasks_path(@connection), notice: 'Task done.'
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    @connection = Connection.find(params[:connection_id])

    redirect_to connection_tasks_path(@connection), status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :end_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="<%= asset_path('logo1.png') %>">
    <title>MentorMe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# Swiper css%>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
  </head>
  <body class="content">
    <div class="content-top">
      <%= render 'shared/navbar' if current_user %>
      <%# <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js"></script> %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' if current_user %>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
  </body>
</html>

app/views/pages/_mentee_dashboard.html.erb
<br>
 <div class="col-xl-8 text-center" id="mentee-profile">

    <div class="card-header"></div>
      <div class="card-body text-center">
                    <!-- Profile picture image-->
        <img class="avatar mb-2" src="<%= current_user.avatar_url %>" alt="">

                    <!-- Profile picture upload button-->
          <button class="btn-ghost btn-submit justify-content-center", id="btn-pp" type="button" style="padding: 10px 20px 28px 20px!important"><strong>Upload new image</strong></button>
      </div>
  <br>

            <!-- Account details card-->
  <%= simple_form_for(@mentee) do |f| %>
    <div class="mb-3">
      <p>First name</p>
      <input class="form-control input_html text-center" id="inputFirstName" type="text" placeholder="<%= current_user.first_name %>" disabled>
    </div>
    <!-- Form last-name-->
    <div class="mb-3">
      <p>Last name</p>
      <input class="form-control input_html text-center" id="inputLastName" type="text" placeholder="<%= current_user.last_name %>" disabled>
    </div>
    <!-- Form email-->
    <div class="mb-3">
      <p>Email</p>
      <input class="form-control input_html text-center" id="inputEmail" type="text" placeholder="<%= current_user.email %>" disabled>
    </div>
    <div class="mb-3">
      <p>Location</p>
      <input class="form-control input_html text-center" id="inputEmail" type="text" placeholder="<%= current_user.location %>" disabled>
    </div>
    <div class="mb-3">
      <p>Bio</p>
      <textarea class="form-control input_html text-center" id="inputbio" type="text" placeholder="<%= current_user.bio %>" disabled></textarea>
    </div>
    <%= f.input :goal,
            required: false,
            placeholder: @mentee.goal,
            input_html: { autocomplete: "goal", class:"input_html text-center form-control" } %>
    <%= f.submit "Update profile", class: "btn-ghost btn-submit justify-content-center mb-3", id:"btn-prim" %>
  <% end %>
  </div>

app/views/pages/_mentor_dashboard.html.erb
<br>
 <div class="col-xl-8 text-center">

     <div class="card-header"></div>
      <div class="card-body text-center">
                    <!-- Profile picture image-->
        <img class="avatar rounded-circle mb-2" src="<%= current_user.avatar_url %>" alt="">

                    <!-- Profile picture upload button-->
          <button class="btn-ghost btn-submit btn-pp justify-content-center" type="button">Upload new image</button>
      </div>
<br>
            <!-- Account details card-->
                    <form>
                        <!-- Form first name (username)-->
                        <div class="mb-3">
                          <p>First name</p>
                          <input class="form-control input_html text-center" id="inputFirstName" type="text" placeholder="<%= current_user.first_name %>" disabled>
                        </div>
                        <!-- Form last-name-->
                        <div class="mb-3">
                          <p>Last name</p>
                          <input class="form-control input_html text-center" id="inputLastName" type="text" placeholder="<%= current_user.last_name %>" disabled>
                        </div>
                        <!-- Form email-->
                        <div class="mb-3">
                          <p>Email</p>
                          <input class="form-control input_html text-center" id="inputEmail" type="text" placeholder="<%= current_user.email %>" disabled>
                        </div>
                        <!-- Form company-->
                        <div class="mb-3">
                          <p>Company</p>
                          <input class="form-control input_html text-center" id="inputCompany" type="text" placeholder="<%= value=current_user.mentor.company %>">
                        </div>
                        <!-- Form job-title-->
                        <div class="mb-3">
                          <p>Job title</p>
                          <input class="form-control input_html text-center" id="inputJobTitle" type="text" placeholder="<%= value=current_user.mentor.job_title %>">
                        </div>
                        <!-- Form location-->
                        <div class="mb-3">
                          <p>Location</p>
                          <input class="form-control input_html text-center" id="inputLocation" type="text" placeholder="Enter your location" value="Amsterdam">
                        </div>
                        <!-- Form bio-->
                        <div class="mb-3">
                          <p>Bio</p>
                          <input class="form-control input_html text-center" id="inputBio" type="text" placeholder="write bio" value="11 years experience as wedeveloper">
                        </div>
                        <div class="form-actions">
                         <button class= "btn-ghost btn-submit justify-content-center" type="button">Save changes</button>
                      </div>
                    </form>
  </div>

app/views/pages/certificate.html.erb
<div class="container-xl px-4 mt-3">
  <div class="achievement-page text-center mb-5">
    <br>
      <strong>
        <h2 class="congratulations" style="color: #548C85 !important; font-family: sans-serif !important; font-size: 50px !important;">Congratulations!</h2>
      </strong>
    <br>
    <%= image_tag "trophy.png", class: "trophy mt-5",  data: {controller: "confetti", action: "click->confetti#spray", confetti_animation_value:"school-pride", confetti_follow_value:"false", confetti_duration_value:"10"}%>
  </div>
  <div class="btn-achievement text-center">
    <div class="btn-achievement text-center" data-controller="socials">
      <%= link_to "Share on socials", "#",  class:"btn-ghost btn-submit btn-achieved justify-content-center mb-3 mt-5", data: {action: 'click->socials#new'}%>
      <div id="socialsmodal" class="modal-container" data-socials-target="socialsmodal">
        <div class="modal-content">
          <span class="new" data-action="click->socials#close">&times;</span>
          <div class="icons-popup">
          <i class="fa-brands social fa-linkedin"></i>
          <i class="fa-brands social fa-square-instagram"></i>
          <i class="fa-brands social fa-square-facebook"></i>
          <i class="fa-brands social fa-square-twitter"></i>
        </div>
        </div>
      </div>
    </div>
    <div class="btn-achievement text-center" data-controller="addreviews">
      <%= link_to "Review your mentor", "#", class:"btn-ghost btn-submit btn-achieved justify-content-center mb-3", data: {action: 'click->addreviews#new'}%>
      <div id="reviewmodal" class="modal-container" data-addreviews-target="reviewmodal">
        <div class="modal-content">
          <span class="new" data-action="click->addreviews#close">&times;</span>
          <%= form_with url: '/certificate' do %>
            <br>
            <br>
            <div class="field">
              <label for="review">Leave your Review:</label>
              <textarea id="review" name="review"></textarea>
            </div>
            <br>
            <div >
              <span data-action="click->addreviews#fill" data-value=0
                class="star">★
              </span>
              <span data-action="click->addreviews#fill" data-value=1
                class="star">★
              </span>
              <span data-action="click->addreviews#fill" data-value=2
                class="star">★
              </span>
              <span data-action="click->addreviews#fill" data-value=3
                class="star">★
              </span>
              <span data-action="click->addreviews#fill" data-value=4
                class="star">★
              </span>
            </div>
            <a href="/certificate">
              <br>
              <input class="submit-review" type="button" value="Submit Review">
            </a>
          <% end %>
        </div>
      </div>
    </div>
    <%= link_to "Choose a new mentor", mentors_path,  class:"btn-ghost btn-submit btn-achieved justify-content-center mb-3"%>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container-xl px-4">

  <% if current_user.is_mentor?%>
  <%= render "mentor_dashboard" %>
  <% else %>
  <%= render "mentee_dashboard" %>
  <% end %>

</div>

app/views/pages/home.html.erb
<div class="container px-4 ">
  <% if current_user.role == 'mentor' %>
    <%= render 'mentors/my_mentees' %>
  <% else %>
    <%= render 'mentees/my_mentors' %>
  <% end %>
</div>

app/views/pages/onboarding.html.erb
<div class="container px-4 mt-4">

  <div class="routes text-center">
    <div class="routes-q mx-10">
      <h5>Who are you?</h5>
    </div>
      <%= link_to "I am a mentor", new_mentor_path, class:"btn btn-flat btn-route"%>
      <%= link_to "I am a mentee", new_mentee_path, class:"btn btn-flat btn-route"%>

  </div>
</div>

app/views/pages/ui_kit.html.erb
<div class="container px-4 mt-4">
<h1>UI Kitt for mentor me</h1>
<p> MAKE ALL HTML FILES INSIDE CLASS="container px-4 mt-4</p>
  <h2>All page titles in this style/also add the hr class=mt-0 mb-4 tag</h2>
    <hr class="mt-0 mb-4">

<p>******************************************</p>

  <h5>Buttons</h5 >
    <p>Sign up / sign in button</p>
  <div class="row">
    <div class="col-12">
        <div class="signup d-flex align-items-center justify-content-center">
          <p><%= link_to "Sign in", "#", class:"btn btn-ghost btn-sign text-center"%></p>
          <p><%= link_to "Sign up", "#", class:"btn btn-ghost btn-sign text-center"%></p>
        </div>
    </div>
  </div>

  <p>All submit buttons</p>
  <div class="row">
    <div class="col-12">
      <%= link_to "Submit", "#",  class:"btn btn-ghost btn-submit d-flex align-items-center justify-content-center"%>
    </div>
  </div>


  <p>Homepage buttons</p>

  <%= link_to "Your profile", "#", class:"btn btn-flat btn-home"%>
  <%= link_to "Find mentor", "#", class:"btn btn-flat btn-home"%>
  <%= link_to "My mentor", "#", class:"btn btn-flat btn-home"%>
  <%= link_to "Timeline", "#", class:"btn btn-flat btn-home"%>

  <p>Reject button</p>
  <%= link_to "Reject", "#", class:"btn btn-flat btn-reject"%>
  <p>Accept button</p>
  <%= link_to "Accept", "#", class:"btn btn-flat btn-accept"%>

  <p>mentor/mentee button</p>
    <%= link_to "I am a mentor", "#", class:"btn btn-flat btn-route"%>
    <%= link_to "I am a mentee", "#", class:"btn btn-flat btn-route"%>
  <br>
  <p>******************************************</p>

  <h5>Avatar</h5>
  <p>still needs to be filled in</p>
  <%# <div class="profile-picture mb-2">
    <%= cl_image_tag current_user.avatar.key, class:"card-img-top rounded-circle", height: 300 if current_user.avatar.attached? %>
  <%# </div> %>
  <br>
  <p>******************************************</p>


  <h5>Cards</h5 >
    <div class="card mb-4 mb-xl-0 card-swipe">
      <div class="card-header">Mentor</div>
        <div class="profile-picture-mentor mb-2">
          <p>mentor picture</p>
        </div>

      <div class="card-body">
        <p>mentor name</p>
        <p>mentor role</p>
        <p>mentor company</p>
        <p>mentor bio</p>
      </div>
    </div>

    <div class="card mb-4 mb-xl-0 card-swipe">
      <div class="card-header">Mentee</div>
        <div class="profile-picture-mentor mb-2">
          <p>mentee picture</p>
        </div>

        <div class="card-body">
          <p>mentee name</p>
          <p>mentee role</p>
          <p>mentee company</p>
          <p>mentee bio</p>
        </div>
    </div>

<p>this card is used for the mentor/mentee en achievements. add class/id en design yourself</p>

<h3>My Mentor</h3>
<h3> Previous Mentors</h3>
<h3>My Mentee</h3>
<h3> Previous Mentees</h3>

<div class="card-small card-small-green">
  <%= link_to "picture of user", "#" %>
  <div class="card-small-infos">
    <h2>user name</h2>
    <i class="fa-regular fa-message fa-3x"></i>
    <p>💬 🏆</p>
  </div>
</div>


    <div class="card-small-gray">
      <%= link_to "picture of user", "#"%>
        <div class="card-small-infos">
          <h2>user name</h2>
          <p>💬   🏆</p>
        </div>
    </div>

<p>******************************************</p>

</div>

app/views/shared/_footer.html.erb
    <div class="footer footer-expand-sm">
      <div class="container-fluid">
        <div class="footer-buttons">

          <%= link_to root_path do %>
            <i class="fa-solid fa-house fa-2x"></i>
          <%end %>

          <%= link_to dashboard_path do %>
            <i class="fa-solid fa-user fa-2x"></i>
          <%end %>

          <%= link_to mentors_path do %>
            <i class="fa-solid fa-magnifying-glass fa-2x"></i>
          <%end %>

          <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
            <i class="fa-solid fa-arrow-right-from-bracket fa-2x"></i>
          <%end %>

        </div>
      </div>
    </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
        <div class="row align-items-center justify-content-between">
            <div class="col-auto">
                <%= image_tag "logo1.png", class: "logo"%>
            </div>
            <div class="col-auto">
                <h2 class="navbar-title mb-0" style="color: #548C85 !important; font-family: sans-serif !important; font-size: 15px !important;">Mentor Me</h2>
            </div>
        </div>
    </div>
</div>