config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # routes for ui kit
  get '/ui_kit', to: 'pages#ui_kit'
  get 'onboarding', to: 'pages#onboarding'
  get '/dashboard', to: 'pages#dashboard'
  post '/connections', to: 'connections#create', as: 'connections'
  get '/certificate', to: 'pages#certificate'



  resources :mentees, only: [:new, :create, :show, :update]
  resources :mentors, only: [:new, :create, :show, :index]

  resources :mentees, only: [:new, :create, :show]
  resources :mentors, only: [:new, :create, :show, :index] do
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews, only: [:show]

  resources :connections, only: [:show] do
    resources :tasks, only: [:index, :new, :create,:show, :destroy,:update]
  end

  resources :tasks, only: [:edit ]
  put 'mark_as_done/:id', to: 'tasks#mark_as_done', as: :mark_as_done_task

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  # resources :tasks do
  #   member do
  #     put 'mark_as_done', to: 'tasks#mark_as_done'
  #   end
  # end
  #   resources :mentors, only: []
  #   resources :rejected, only: []
  # end
  # resources :connections, only: [] do
  #   resources :tasks, only: []
  # end
  # resources :chatrooms, only: [] do
  #   resources :messages, only: []
  # end
  # Defines the root path route ("/")
  # root "posts#index"

end

app/models/mentor.rb
class Mentor < ApplicationRecord
  belongs_to :user
  has_one :connection, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :job_title, presence: true
  validates :company, presence: true
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController

  def index
    @mentors = Mentor.all
    @connection = Connection.new
    @reviews = Review.all
  end

  def new
    @mentor = Mentor.new
  end

  def create
    @mentor = Mentor.new(mentor_params)
    @mentor.user = current_user
    @mentor.save

    redirect_to root_path
  end

  def show
    @mentor = Mentor.find(params[:id])
  end

  private

  def mentor_params
    params.require(:mentor).permit(:job_title, :company)
  end
end

app/views/mentors/_my_mentees.html.erb
<div class="container px-4 mt-4">
  <h2 class="mt-0 mb-4">My Mentee</h2>

  <div class="card-small card-small-green">
    <% if @connection %>
      <%= link_to image_tag('https://via.placeholder.com/75', alt: 'User Avatar', style: 'border-radius: 20px;'), connection_path(@connection) if @connection %>
    <% end %>
    <div class="card-small-infos">
      <% if @connection %>
        <h4><%= @connection.mentee.user.first_name %></h4>
      <% else %>
        <h4><%= link_to 'choose your mentee', mentees_path %></h4>
      <% end %>
    </div>
    <% if @connection %>
      <%= link_to chatroom_path(Chatroom.last) do %>
       <svg xmlns="http://www.w3.org/2000/svg" class="message-icon-mentor" width="34" height="34" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"/></svg>
      <% end %>
      <%= link_to connection_tasks_path(@connection) do %>
        <i class="timeline-icon fa-regular fa-calendar-days"></i>
      <% end %>
    <% end %>
  </div>

  <br>

  <h2 class="mt-0 mb-4"> Previous Mentees</h2>

  <div class="card-small-gray">
    <%= link_to image_tag('https://via.placeholder.com/75', alt: 'User Avatar', style: 'border-radius: 20px;'), connection_path(@connection) if @connection %>
    <div class="card-small-infos">
      <h4 class="gray-username">user name</h4>
      <i class="message-icon-gray fa-regular fa-message fa-2x"></i>
      <i class="timeline-icon-gray fa-regular fa-calendar-days"></i>
    </div>
  </div>

  <div class="card-small-gray">
    <%= link_to image_tag('https://via.placeholder.com/75', alt: 'User Avatar', style: 'border-radius: 20px;'), connection_path(@connection) if @connection %>
    <div class="card-small-infos">
      <h4 class="gray-username">user name</h4>
      <i class="message-icon-gray fa-regular fa-message fa-2x"></i>
      <i class="timeline-icon-gray fa-regular fa-calendar-days"></i>
    </div>
  </div>

  <div class="card-small-gray">
    <%= link_to image_tag('https://via.placeholder.com/75', alt: 'User Avatar', style: 'border-radius: 20px;'), connection_path(@connection) if @connection %>
    <div class="card-small-infos">
      <h4 class="gray-username">user name</h4>
      <i class="message-icon-gray fa-regular fa-message fa-2x"></i>
      <i class="timeline-icon-gray fa-regular fa-calendar-days"></i>
    </div>
  </div>
</div>

app/views/mentors/_show.html.erb
<div class="container px-4 mt-4">
<h3 class="mt-0 mb-4">My Mentee</h3>

<div class="card-small card-small-green">
  <%= link_to "picture of user", "#" %>
  <div class="card-small-infos">
    <h2>user name</h2>
    <p>💬 🏆</p>
  </div>
</div>

<br>

<h3 class="mt-0 mb-4"> Previous Mentees</h3>

    <div class="card-small-gray">
      <%= link_to "picture of user", "#"%>
        <div class="card-small-infos">
          <h2>user name</h2>
          <p>💬   🏆</p>
        </div>
    </div>

  <div class="card-small-gray">
      <%= link_to "picture of user", "#"%>
        <div class="card-small-infos">
          <h2>user name</h2>
          <p>💬   🏆</p>
        </div>
    </div>

      <div class="card-small-gray">
      <%= link_to "picture of user", "#"%>
        <div class="card-small-infos">
          <h2>user name</h2>
          <p>💬   🏆</p>
        </div>
    </div>
</div>

app/views/mentors/_show_mentee.html.erb
<% if current_user === @mentee.user %>
    <% photo = @mentor.user.avatar_url %>
<% else %>
    <% photo = @mentee.user.avatar_url %>
<% end %>
 <div class="col-xl-8 text-center">

     <div class="card-header"></div>
      <div class="card-body text-center">
                    <!-- Profile picture image-->
        <img class="avatar rounded-circle mb-2" src="<%= photo %>" alt="">
      </div>
<br>
            <!-- Account details card-->
                    <form>
                        <!-- Form first name (username)-->
                        <div class="mb-3">
                          <p>First name</p>
                          <input class="form-control input_html text-center" id="inputFirstName" type="text" placeholder="<%= @mentee.user.first_name %>" disabled>
                        </div>
                        <!-- Form last-name-->
                        <div class="mb-3">
                          <p>Last name</p>
                          <input class="form-control input_html text-center" id="inputLastName" type="text" placeholder="<%= @mentee.user.last_name %>" disabled>
                        </div>
                        <!-- Form email-->
                        <div class="mb-3">
                          <p>Email</p>
                          <input class="form-control input_html text-center" id="inputEmail" type="text" placeholder="<%= @mentee.user.email %>" disabled>
                        </div>
                        <!-- Form company-->
                        <div class="mb-3">
                          <p>Goal</p>
                          <input class="form-control input_html text-center" id="inputGoal" type="text" placeholder="<%= value=@mentee.goal %>">
                        </div>
                        <!-- Form location-->
                        <div class="mb-3">
                          <p>Location</p>
                          <input class="form-control input_html text-center" id="inputLocation" type="text" placeholder="Enter your location" value="Amsterdam">
                        </div>
                        <!-- Form bio-->
                        <div class="mb-3">
                          <p>Bio</p>
                          <input class="form-control input_html text-center" id="inputBio" type="text" placeholder="write bio" value="11 years experience as wedeveloper">
                        </div>
                        <div class="form-actions">
                         <button class= "btn-ghost btn-submit justify-content-center" type="button">Save changes</button>
                      </div>
                    </form>
  </div>

app/views/mentors/index.html.erb
<br>
<div class="container px-4" data-controller='swiper reviews'>

  <!-- The Modal -->
  <% @mentors.each do |mentor| %>
    <div id="myModal" class="modal-container" data-reviews-target="modal" data-mentor-id="<%= mentor.id %>">
      <!-- Modal content -->
      <div class="modal-content">
        <span class="close" data-action="click->reviews#close" data-mentor-id="<%= mentor.id %>">&times;</span>
          <%mentor.reviews.each do |review| %>
          <span class="gold">
          <% (1..5).each do |i| %>
            <% if i <= review.rating %>
            <%=  raw '&#9733;' %> <!-- This is a filled star -->
            <% else %>
             <%= raw '&#9734;' %> <!-- This is an empty star -->
            <% end %>
          <% end %>
          </span>
            <p><%= review.content %></p>
            <p class="user-review"><em>-Anonymous</em></p>
            <hr class="mt-0 mb-4">
          <% end %>
      </div>
    </div>
  <% end %>




<div class="swiper mySwiper">
  <div class="swiper-pagination"></div>
  <div class="swiper-wrapper">
    <% @mentors.each do |mentor| %>
      <div class="swiper-slide text-center">

         <%= image_tag mentor.user.avatar_url, class:"avatar-swipe " %>

         <div id="popup-link"  data-action="click->reviews#show" data-mentor-id="<%= mentor.id %>">
          <p class="btn-ghost btn-submit btn-review justify-content-center" id=star-review><strong>Reviews</strong></p>
        </div>

      <form class="bio mt-4">
        <input class="form-control input_html text-center swipe-input" id="import-input" type="text" placeholder="<%= value=mentor.user.first_name%> <%= value=mentor.user.last_name%>" disabled>
        <input class="form-control input_html text-center swipe-input" id="inputCompany" type="text" placeholder="<%= value=mentor.job_title %>" disabled>
        <input class="form-control input_html text-center swipe-input" id="inputCompany" type="text" placeholder="<%= value=mentor.company %>" disabled>
        <input class="form-control input_html text-center swipe-input" id="inputCompany" type="text" placeholder="<%= value=mentor.user.location %>" disabled></p>
        <textarea class="form-control input_html text-center swipe-input" id="inputCompany" placeholder="<%= mentor.user.bio %>" disabled rows="8" cols="50"></textarea>
        </form>

      </div>
    <% end %>
  </div>

</div>

<div class="buttons">
  <button class="btn btn-flat btn-reject">Reject</button>
  <button type="submit"  class="btn btn-flat btn-accept">Accept</button>
</div>
</div>

app/views/mentors/new.html.erb
<div class="container px-4 mt-4">
  <h2>Mentor</h2>
    <hr class="mt-0 mb-4">

  <%= simple_form_for(@mentor, html: { multipart: true }) do |f| %>
  <div class="form-inputs text-center">
    <%= f.input :job_title,
                required: false,
                placeholder: "'developer'",
                input_html: { autocomplete: "location", class:"input_html text-center" } %>
     <%= f.input :company,
                required: false,
                placeholder: "'Google'",
                input_html: { autocomplete: "location", class:"input_html text-center" } %>
      <div class="form-actions">
      <%= f.button :submit, "Create account", class: "btn btn-ghost btn-submit row justify-content-center" %>
      </div>
  <% end %>
  </div>
</div>

app/views/mentors/show.html.erb
<div class="container px-4 mt-4">
<h3 class="mt-0 mb-4">My Mentee</h3>

<div class="card-small card-small-green">
  <%= link_to "picture of user", "#" %>
  <div class="card-small-infos">
    <h2>user name</h2>
    <p>💬 🏆</p>
  </div>
</div>

<br>

<h3 class="mt-0 mb-4"> Previous Mentees</h3>

    <div class="card-small-gray">
      <%= link_to "picture of user", "#"%>
        <div class="card-small-infos">
          <h2>user name</h2>
          <p>💬   🏆</p>
        </div>
    </div>

  <div class="card-small-gray">
      <%= link_to "picture of user", "#"%>
        <div class="card-small-infos">
          <h2>user name</h2>
          <p>💬   🏆</p>
        </div>
    </div>

      <div class="card-small-gray">
      <%= link_to "picture of user", "#"%>
        <div class="card-small-infos">
          <h2>user name</h2>
          <p>💬   🏆</p>
        </div>
    </div>
</div>